# Generated by Django 2.2.1 on 2019-05-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
            ],
        ),
    ]
