# Generated by Django 2.2.1 on 2019-05-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursetitle', models.CharField(max_length=50)),
                ('courseid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=40)),
                ('instructorid', models.CharField(max_length=50)),
                ('courseid', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='username',
            new_name='instructorid',
        ),
    ]
